
steps:
  - name: ":cloudformation: :runner: elastic-runners-new"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-runners-new
    artifact_paths: "output.json"

  - wait
  - name: ":cloudformation: :building_construction: elastic-builders"
    agents:
      stack: elastic-runners-new
    command: ./update-stack.sh elastic-builders
    artifact_paths: "output.json"

  - wait
  - name: ":cloudformation: :chart_with_upwards_trend: elastic-pipeline-uploaders"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-pipeline-uploaders
    artifact_paths: "output.json"
