
steps:
  - name: ":cloudformation: :runner: elastic-runners"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-runners
    artifact_paths: "output.json"
    concurrency: 1
    concurrency_group: "elastic-stack-update"

  - wait
  - name: ":cloudformation: :building_construction: elastic-builders"
    agents:
      stack: elastic-runners
    command: ./update-stack.sh elastic-builders
    artifact_paths: "output.json"
    concurrency: 1
    concurrency_group: "elastic-stack-update"

  - wait
  - name: ":cloudformation: :chart_with_upwards_trend: elastic-pipeline-uploaders"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-pipeline-uploaders
    artifact_paths: "output.json"
    concurrency: 1
    concurrency_group: "elastic-stack-update"
