
steps:
  - name: ":cloudformation: :building_construction: elastic-builders"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-builders

  - wait
  - name: ":cloudformation: :chart_with_upwards_trend: elastic-pipeline-uploaders"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-pipeline-uploaders

  - wait
  - name: ":cloudformation: :runner: elastic-runners-new"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-runners-new