
steps:
  - name: ":aws: elastic-builders"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-builders

  - wait
  - name: ":aws: elastic-pipeline-uploaders"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-pipeline-uploaders

  - wait
  - name: ":aws: elastic-runners-new"
    agents:
      queue: elastic-builders
    command: ./update-stack.sh elastic-runners-new